eth_contract:
	abigen --abi=./solidity/DvNft.abi --pkg=main --out=./solidity/eth_nft_smart.go
	abigen --abi=./solidity/DvNftMarket.abi --pkg=main --out=./solidity/eth_nft_market_smart.go

rarible_contract:
	abigen --abi=./solidity/RaribleNft.abi --pkg=main --out=./solidity/rarible_nft_smart.go